export enum MessageAction {
  SERVICE_WORKER_LOG = "SERVICE_WORKER_LOG",
  CONTENT_LOG = "CONTENT_LOG",
}

export enum Caller {
  SERVICE_WORKER = "SERVICE_WORKER",
  CONTENT_SCRIPT = "CONTENT_SCRIPT",
  POPUP_EXTENSION = "POPUP_EXTENSION",
}